version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: protoc-gen-utcp
    main: ./cmd/protoc-gen-utcp
    binary: protoc-gen-utcp
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE
      - README.md
      - CONTRIBUTING.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - '^build:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Performance Improvements
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

release:
  github:
    owner: dimelords
    name: protoc-gen-utcp
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
  header: |
    ## Installation

    ### Using go install
    ```bash
    go install github.com/dimelords/protoc-gen-utcp/cmd/protoc-gen-utcp@{{ .Tag }}
    ```

    ### Download binary
    Download the appropriate binary for your platform from the assets below.

  footer: |
    ## What's Changed
    See the changelog above for details.

    **Full Changelog**: https://github.com/dimelords/protoc-gen-utcp/compare/{{ .PreviousTag }}...{{ .Tag }}

# Homebrew formula publishing
# Note: 'brews' is still the correct field name in GoReleaser v2
# The deprecation warning refers to it being phased out in favor of separate tap repos
brews:
  - repository:
      owner: dimelords
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/dimelords/protoc-gen-utcp
    description: "Protocol Buffer compiler plugin that generates UTCP definitions"
    license: MIT
    skip_upload: auto
    install: |
      bin.install "protoc-gen-utcp"
    test: |
      system "#{bin}/protoc-gen-utcp", "-version"
